### ISSUE TITLE
Resolve "black screen" issue on the XO

### ISSUE THREAD

**Issue by justwheel** [FOSSRIT/PyCut#12] opened 2016-04-20 13:47 UTC
When we try building and deploying the game on the XO, the game will present a black screen without any usable interface. This is not the case when the game is run on normal hardware, like Linux desktop environment (on my system, at least). It seems like there are unknown factors contributing to running the game on the XO / Sugar that are preventing us from running the game.

**Comment by wilfriedE** [comment] 2016-04-27 21:04
@jflory7 can you include the stack trace bellow here for the issue?

**Comment by justwheel** [comment] 2016-04-27 23:55
@wilfriedE Actually, with commit 108736657b2b153c20537f9a8010dbf3fc7d17ec, this issue is now resolved. When we installed `enum34`, everything ran as expected. :) Issue resolved!

:clapper:

**Comment by adf5051** [comment] 2016-12-15 01:10
https://github.com/tcreeds/PyCut/issues/4 for discussion history.

This still seems to be an issue and enum34 did not work for any of our XOs in regard to the black screen.

**Comment by quozl** [comment] 2016-12-22 06:12
I've had a quick look at this for you, after a chance discovery of your changes on the Sugar Labs Wiki.

Firstly, the black screen reminds me of an interaction between the activity and sugargame, and the log shows an interesting warning from sugargame about pygame order of initialisation.  It can be interactively replicated with `sugar-activity .` in the Terminal while current working directory is a clone of PyCut.  I've reviewed all the copies of sugargame that I've got; the Gitorious instance at Sugar Labs, the Physics activity, Develop activity, and XoPhoto activity, trying to restore some sense of history.  But failed.  My guess is that PyCutActivity.py should be recast against a more recent sugargame and use the second example TestGame.py.

Secondly, I've removed the dependency on `import enum` with a few small changes; the full features of enum are not being used by your code, so it was easy to hack it up.  Please cherry-pick 2380f0268c05273043f8c0f2cb2da7ee8f6ed469 or tell me if you'd like a pull-request.

**Comment by wilfriedE** [comment] 2016-12-23 05:11
@quozl A pull-request would be preferred. Thank you for taking a look at this. :+1:

**Comment by quozl** [comment] 2016-12-23 05:24
@wilfriedE, done.

**Comment by justwheel** [comment] 2017-01-17 00:08
@quozl In lieu of the recent PR we just merged in, would you be able to test the latest changes and verify the black screen is fixed? If not, we might be able to see if @ritjoe is able to assist with this.

**Comment by quozl** [comment] 2017-01-17 00:25
@jflory7, commit 4b5c42fd11cf0cca51652b91aa3966e1377a456e does continue to black-screen on Sugar 0.110 on Ubuntu 16.04 in a VM, and on Fedora 18 on an XO-4.

Logs from Ubuntu 16.04:
```
/home/guest/Activities/pycut-activity/PyCutActivity.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/home/guest/Activities/pycut-activity/sugargame/canvas.py", line 43, in _run_pygame_cb
    assert pygame.display.get_init() == False, "Pygame must not be initialized before calling PygameCanvas.run_pygame."
AssertionError: Pygame must not be initialized before calling PygameCanvas.run_pygame.
```

Logs from Fedora 18:
```
Traceback (most recent call last):
  File "/home/olpc/Activities/pycut-activity/sugargame/canvas.py", line 58, in _run_pygame_cb
    main_fn()
  File "/home/olpc/Activities/pycut-activity/game/__init__.py", line 98, in run
    self.game_loop()
  File "/home/olpc/Activities/pycut-activity/game/__init__.py", line 90, in game_loop
    self.active_scene.Render()
  File "/home/olpc/Activities/pycut-activity/game/scenes/title_scene.py", line 41, in Render
    self.screen.fill((255, 255, 255))
AttributeError: 'NoneType' object has no attribute 'fill'
```

Very different logs suggest very different underlying problems.

Also, running the PyCut.py file in Terminal:
```
Traceback (most recent call last):
  File "PyCut.py", line 13, in <module>
    main()
  File "PyCut.py", line 10, in main
    game_instance.run()
  File "/home/guest/Activities/pycut-activity/game/__init__.py", line 98, in run
    self.game_loop()
  File "/home/guest/Activities/pycut-activity/game/__init__.py", line 90, in game_loop
    self.active_scene.Render()
  File "/home/guest/Activities/pycut-activity/game/scenes/title_scene.py", line 46, in Render
    self.score_msg.drawOn(self.screen)
  File "/home/guest/Activities/pycut-activity/game/objects/text.py", line 78, in drawOn
    if self.centered:
AttributeError: Text instance has no attribute 'centered'
```

**Comment by wilfriedE** [comment] 2017-01-17 00:46
I submitted a pull request to @tcreeds's fork that has a fix for the lack screen issue: https://github.com/tcreeds/PyCut/pull/14 

I found that one of the issue is that the assets were not using the proper paths. 
The other is that pygame doesn't get initialized properly. 

Tested the fix on a Sugar VM and it worked however non of the buttons work.

/cc @jflory7

**Comment by quozl** [comment] 2017-01-17 01:11
@wilfriedE, thanks, on Ubuntu 16.04 with 4b5c42f plus a `git cherry-pick -n 82b2deb 7c2a69b e83a89c` from your pull request, the "*AssertionError:  Pygame must not be initialized*" is fixed, and the "*AttributeError: Text instance has no attribute 'centered'*" is revealed.  Testing your e83a89c alone shows the menu, but there is no response to clicks.

**Comment by wilfriedE** [comment] 2017-01-17 01:45
@quozl, temporarily created an attribute for centered. Still unsure why none of the clicks are responding, but will look at this more later this week.

**Comment by wilfriedE** [comment] 2017-01-21 03:29
@jflory7 @quozl going to close this issue and move conversations regarding the non responsive buttons to #42 .

**Closed as completed by wilfriedE** 2017-01-21 03:29 UTC
Labels: bug, help wanted
